# Generated by Django 4.0.6 on 2022-11-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bkID', models.IntegerField(primary_key=True, serialize=False)),
                ('bkCode', models.CharField(max_length=20)),
                ('bkName', models.CharField(max_length=50)),
                ('bkAuthor', models.CharField(max_length=30)),
                ('bkStatus', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ReaderType',
            fields=[
                ('rdType', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rdTypeName', models.CharField(max_length=20, unique=True)),
                ('CanLendQty', models.IntegerField()),
                ('CanLendDay', models.IntegerField()),
                ('CanContinueTimes', models.IntegerField()),
                ('PunishRate', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('rdID', models.IntegerField(primary_key=True, serialize=False)),
                ('rdName', models.CharField(max_length=20)),
                ('rdSex', models.IntegerField()),
                ('rdDept', models.CharField(max_length=20)),
                ('rdPhone', models.CharField(max_length=11)),
                ('rdEmail', models.CharField(max_length=25)),
                ('rdDateReg', models.DateTimeField()),
                ('rdStatus', models.CharField(max_length=2)),
                ('rdBorrowQty', models.IntegerField()),
                ('rdPwd', models.CharField(max_length=25)),
                ('rdAdminRoles', models.SmallIntegerField()),
                ('rdType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.readertype')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('BorrowID', models.IntegerField(primary_key=True, serialize=False)),
                ('IdContinueTimes', models.IntegerField()),
                ('ldDateOut', models.DateTimeField()),
                ('ldDateRetPlan', models.DateTimeField()),
                ('ldDateRetAct', models.DateTimeField()),
                ('bkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.book')),
                ('rdID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.reader')),
            ],
        ),
    ]
