# Generated by Django 4.0.6 on 2022-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='rdAdminRoles',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdBorrowQty',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdDateReg',
            field=models.DateTimeField(verbose_name='读者登记日期'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdDept',
            field=models.CharField(max_length=20, verbose_name='读者单位'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdEmail',
            field=models.CharField(max_length=25, verbose_name='读者邮箱'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='读者ID'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdName',
            field=models.CharField(max_length=20, verbose_name='读者姓名'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdPhone',
            field=models.CharField(max_length=11, verbose_name='读者电话'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdPwd',
            field=models.CharField(max_length=25, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdSex',
            field=models.IntegerField(verbose_name='读者性别'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdStatus',
            field=models.CharField(max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='readertype',
            name='CanContinueTimes',
            field=models.IntegerField(verbose_name='可续借的次数'),
        ),
        migrations.AlterField(
            model_name='readertype',
            name='CanLendDay',
            field=models.IntegerField(verbose_name='可借书天数'),
        ),
        migrations.AlterField(
            model_name='readertype',
            name='CanLendQty',
            field=models.IntegerField(verbose_name='可借书数量'),
        ),
        migrations.AlterField(
            model_name='readertype',
            name='PunishRate',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='罚款率'),
        ),
        migrations.AlterField(
            model_name='readertype',
            name='rdType',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='读者类型'),
        ),
        migrations.AlterField(
            model_name='readertype',
            name='rdTypeName',
            field=models.CharField(max_length=20, unique=True, verbose_name='读者类型名'),
        ),
    ]
