# Generated by Django 4.0.6 on 2022-11-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_reader_rdadminroles_alter_reader_rdborrowqty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='rdAdminRoles',
            field=models.SmallIntegerField(choices=[(0, '读者'), (1, '借书证管理'), (2, '图书管理'), (4, '借阅管理'), (8, '系统管理')], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdSex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='读者性别'),
        ),
        migrations.AlterField(
            model_name='readertype',
            name='rdType',
            field=models.SmallIntegerField(choices=[(0, '教师'), (1, '本科生'), (2, '专科生'), (3, '研究生'), (4, '博士生')], primary_key=True, serialize=False, verbose_name='读者类型'),
        ),
    ]
