# Generated by Django 4.0.6 on 2022-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_reader_rdadminroles_alter_reader_rdsex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readertype',
            name='rdType',
            field=models.CharField(choices=[(0, '教师'), (1, '本科生'), (2, '专科生'), (3, '研究生'), (4, '博士生')], max_length=10, primary_key=True, serialize=False, verbose_name='读者类型'),
        ),
    ]
