# Generated by Django 4.0.6 on 2022-11-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_readertype_rdtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bkAuthor',
            field=models.CharField(max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bkCode',
            field=models.CharField(max_length=20, verbose_name='IBSN码'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bkID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='图书编号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bkName',
            field=models.CharField(max_length=50, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bkStatus',
            field=models.CharField(max_length=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='BorrowID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='IdContinueTimes',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='ldDateOut',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='ldDateRetAct',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='ldDateRetPlan',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdAdminRoles',
            field=models.SmallIntegerField(choices=[(0, '读者'), (1, '借书证管理'), (2, '图书管理'), (4, '借阅管理'), (8, '系统管理')], verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdBorrowQty',
            field=models.IntegerField(verbose_name='可借书天数'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdPwd',
            field=models.CharField(max_length=25, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdStatus',
            field=models.CharField(max_length=2, verbose_name='状态'),
        ),
    ]
