# Generated by Django 4.0.6 on 2022-12-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_book_bkauthor_alter_book_bkcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='BorrowID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='借书证号'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='IdContinueTimes',
            field=models.IntegerField(verbose_name='可借阅时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='ldDateOut',
            field=models.DateTimeField(verbose_name='借书时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='ldDateRetAct',
            field=models.DateTimeField(verbose_name='实际还书日期'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='ldDateRetPlan',
            field=models.DateTimeField(verbose_name='应还时间'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rdID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='读者ID'),
        ),
    ]
