# Generated by Django 4.0.6 on 2022-12-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_borrow_borrowid_alter_borrow_idcontinuetimes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='BorrowID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='借书顺序号'),
        ),
    ]
